name: first
on: [push]

jobs:
  job1:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: step one
        uses: actions/checkout@v4

      - name: step two
        run: env | sort

  job2:
    name: second job
    runs-on: windows-latest
    steps:
      - name: step one
        uses: actions/checkout@v4

      - name: step two
        run: env | sort
      - name: AWS Sustainability Scanner GitHub Action
       # You may pin to the exact commit or the version.
         # uses: aws-actions/sustainability-scanner@d6067411fc5290a836e3ebcf388c746d83cf0e9f
        uses: aws-actions/sustainability-scanner@v1
        with:
    # File path of the CloudFormation template to be scanned
        file: # optional
    # Directory path with CloudFormation files to be scanned
      
          
